# require('json2ify')
# require('es5-shimify')
require('jqueryify')
require('lib/jquery-ui')
require('lib/handlebars')
require('utils/handlebar-helpers')

require('spine')
require('spine/lib/local')
# require('spine/lib/ajax')
# require('spine/lib/manager')
# require('spine/lib/route')
