/* Copyright 2012 Twitter, Inc.
 * Licensed under the Apache License, Version 2.0
 */

/* bootstrap-modal.js v2.0.4 */
!function(b){function k(){var a=this,c=setTimeout(function(){a.$element.off(b.support.transition.end);g.call(a)},500);this.$element.one(b.support.transition.end,function(){clearTimeout(c);g.call(a)})}function g(){this.$element.hide().trigger("hidden");h.call(this)}function h(a){var c=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var d=b.support.transition&&c;this.$backdrop=b('<div class="modal-backdrop '+c+'" />').appendTo(document.body);"static"!=this.options.backdrop&&
this.$backdrop.click(b.proxy(this.hide,this));d&&this.$backdrop[0].offsetWidth;this.$backdrop.addClass("in");d?this.$backdrop.one(b.support.transition.end,a):a()}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),b.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(b.support.transition.end,b.proxy(i,this)):i.call(this)):a&&a()}function i(){this.$backdrop.remove();this.$backdrop=null}function j(){var a=this;if(this.isShown&&this.options.keyboard)b(document).on("keyup.dismiss.modal",
function(b){27==b.which&&a.hide()});else this.isShown||b(document).off("keyup.dismiss.modal")}var f=function(a,c){this.options=c;this.$element=b(a).delegate('[data-dismiss="modal"]',"click.dismiss.modal",b.proxy(this.hide,this))};f.prototype={constructor:f,toggle:function(){return this[!this.isShown?"show":"hide"]()},show:function(){var a=this,c=b.Event("show");this.$element.trigger(c);!this.isShown&&!c.isDefaultPrevented()&&(b("body").addClass("modal-open"),this.isShown=!0,j.call(this),h.call(this,
function(){var c=b.support.transition&&a.$element.hasClass("fade");a.$element.parent().length||a.$element.appendTo(document.body);a.$element.show();c&&a.$element[0].offsetWidth;a.$element.addClass("in");c?a.$element.one(b.support.transition.end,function(){a.$element.trigger("shown")}):a.$element.trigger("shown")}))},hide:function(a){a&&a.preventDefault();a=b.Event("hide");this.$element.trigger(a);this.isShown&&!a.isDefaultPrevented()&&(this.isShown=!1,b("body").removeClass("modal-open"),j.call(this),
this.$element.removeClass("in"),b.support.transition&&this.$element.hasClass("fade")?k.call(this):g.call(this))}};b.fn.modal=function(a){return this.each(function(){var c=b(this),d=c.data("modal"),e=b.extend({},b.fn.modal.defaults,c.data(),"object"==typeof a&&a);d||c.data("modal",d=new f(this,e));if("string"==typeof a)d[a]();else e.show&&d.show()})};b.fn.modal.defaults={backdrop:!0,keyboard:!0,show:!0};b.fn.modal.Constructor=f;b(function(){b("body").on("click.modal.data-api",'[data-toggle="modal"]',
function(a){var c=b(this),d,e=b(c.attr("data-target")||(d=c.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"")),c=e.data("modal")?"toggle":b.extend({},e.data(),c.data());a.preventDefault();e.modal(c)})})}(window.jQuery);

/* bootstrap-dropdown.js v2.0.4 */
!function(c){function f(){c(g).parent().removeClass("open")}var g='[data-toggle="dropdown"]',d=function(b){var a=c(b).on("click.dropdown.data-api",this.toggle);c("html").on("click.dropdown.data-api",function(){a.parent().removeClass("open")})};d.prototype={constructor:d,toggle:function(){var b=c(this),a;if(!b.is(".disabled, :disabled"))return a=b.attr("data-target"),a||(a=(a=b.attr("href"))&&a.replace(/.*(?=#[^\s]*$)/,"")),a=c(a),a.length||(a=b.parent()),b=a.hasClass("open"),f(),b||a.toggleClass("open"),
!1}};c.fn.dropdown=function(b){return this.each(function(){var a=c(this),e=a.data("dropdown");e||a.data("dropdown",e=new d(this));"string"==typeof b&&e[b].call(a)})};c.fn.dropdown.Constructor=d;c(function(){c("html").on("click.dropdown.data-api",f);c("body").on("click.dropdown",".dropdown form",function(b){b.stopPropagation()}).on("click.dropdown.data-api",g,d.prototype.toggle)})}(window.jQuery);

/* bootstrap-tab.js v2.0.2 */
!function(c){var e=function(a){this.element=c(a)};e.prototype={constructor:e,show:function(){var a=this.element,f=a.closest("ul:not(.dropdown-menu)"),b=a.attr("data-target"),g,d;b||(b=(b=a.attr("href"))&&b.replace(/.*(?=#[^\s]*$)/,""));a.parent("li").hasClass("active")||(g=f.find(".active a").last()[0],d=c.Event("show",{relatedTarget:g}),a.trigger(d),d.isDefaultPrevented()||(b=c(b),this.activate(a.parent("li"),f),this.activate(b,b.parent(),function(){a.trigger({type:"shown",relatedTarget:g})})))},
activate:function(a,f,b){function g(){d.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");a.addClass("active");e?(a[0].offsetWidth,a.addClass("in")):a.removeClass("fade");a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active");b&&b()}var d=f.find("> .active"),e=b&&c.support.transition&&d.hasClass("fade");e?d.one(c.support.transition.end,g):g();d.removeClass("in")}};c.fn.tab=function(a){return this.each(function(){var f=c(this),b=f.data("tab");b||f.data("tab",
b=new e(this));if("string"==typeof a)b[a]()})};c.fn.tab.Constructor=e;c(function(){c("body").on("click.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(a){a.preventDefault();c(this).tab("show")})})}(window.jQuery);