/*! Socket.IO.js build:0.8.7, development. Copyright(c) 2011 LearnBoost <dev@learnboost.com> MIT Licensed */

/**
 * socket.io
 * Copyright(c) 2011 LearnBoost <dev@learnboost.com>
 * MIT Licensed
 */

(function(g,d){g.version="0.8.7";g.protocol=1;g.transports=[];g.j=[];g.sockets={};g.connect=function(e,a){var f=g.util.parseUri(e),c,b;d&&d.location&&(f.protocol=f.protocol||d.location.protocol.slice(0,-1),f.host=f.host||(d.document?d.document.domain:d.location.hostname),f.port=f.port||d.location.port);c=g.util.uniqueUri(f);var h={host:f.host,secure:"https"==f.protocol,port:f.port||("https"==f.protocol?443:80),query:f.query||""};g.util.merge(h,a);if(h["force new connection"]||!g.sockets[c])b=new g.Socket(h);
!h["force new connection"]&&b&&(g.sockets[c]=b);b=b||g.sockets[c];return b.of(1<f.path.length?f.path:"")}})("object"===typeof module?module.exports:this.io={},this);
(function(g,d){var e=g.util={},a=/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,f="source,protocol,authority,userInfo,user,password,host,port,relative,path,directory,file,query,anchor".split(",");e.parseUri=function(b){for(var b=a.exec(b||""),h={},c=14;c--;)h[f[c]]=b[c]||"";return h};e.uniqueUri=function(b){var h=b.protocol,c=b.host,b=b.port;"document"in
d?(c=c||document.domain,b=b||("https"==h&&"https:"!==document.location.protocol?443:document.location.port)):(c=c||"localhost",!b&&"https"==h&&(b=443));return(h||"http")+"://"+c+":"+(b||80)};e.query=function(b,h){var c=e.chunkQuery(b||""),a=[];e.merge(c,e.chunkQuery(h||""));for(var f in c)c.hasOwnProperty(f)&&a.push(f+"="+c[f]);return a.length?"?"+a.join("&"):""};e.chunkQuery=function(b){for(var h={},b=b.split("&"),c=0,a=b.length,f;c<a;++c)f=b[c].split("="),f[0]&&(h[f[0]]=decodeURIComponent(f[1]));
return h};var c=!1;e.load=function(b){if("document"in d&&"complete"===document.readyState||c)return b();e.on(d,"load",b,!1)};e.on=function(b,c,a,f){b.attachEvent?b.attachEvent("on"+c,a):b.addEventListener&&b.addEventListener(c,a,f)};e.request=function(b){if(b&&"undefined"!=typeof XDomainRequest)return new XDomainRequest;if("undefined"!=typeof XMLHttpRequest&&(!b||e.ua.hasCORS))return new XMLHttpRequest;if(!b)try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}return null};"undefined"!=typeof window&&
e.load(function(){c=!0});e.defer=function(b){if(!e.ua.webkit||"undefined"!=typeof importScripts)return b();e.load(function(){setTimeout(b,100)})};e.merge=function(b,c,a,f){var f=f||[],a="undefined"==typeof a?2:a,d;for(d in c)c.hasOwnProperty(d)&&0>e.indexOf(f,d)&&("object"!==typeof b[d]||!a?(b[d]=c[d],f.push(c[d])):e.merge(b[d],c[d],a-1,f));return b};e.mixin=function(b,c){e.merge(b.prototype,c.prototype)};e.inherit=function(b,c){function a(){}a.prototype=c.prototype;b.prototype=new a};e.isArray=Array.isArray||
function(b){return"[object Array]"===Object.prototype.toString.call(b)};e.intersect=function(b,c){for(var a=[],f=b.length>c.length?b:c,d=b.length>c.length?c:b,i=0,r=d.length;i<r;i++)~e.indexOf(f,d[i])&&a.push(d[i]);return a};e.indexOf=function(b,c,a){if(Array.prototype.indexOf)return Array.prototype.indexOf.call(b,c,a);for(var f=b.length,a=0>a?0>a+f?0:a+f:a||0;a<f&&b[a]!==c;a++);return f<=a?-1:a};e.toArray=function(b){for(var c=[],a=0,f=b.length;a<f;a++)c.push(b[a]);return c};e.ua={};e.ua.hasCORS=
"undefined"!=typeof XMLHttpRequest&&function(){try{var b=new XMLHttpRequest}catch(c){return!1}return void 0!=b.withCredentials}();e.ua.webkit="undefined"!=typeof navigator&&/webkit/i.test(navigator.userAgent)})("undefined"!=typeof io?io:module.exports,this);
(function(g,d){function e(){}g.EventEmitter=e;e.prototype.on=function(a,f){this.$events||(this.$events={});this.$events[a]?d.util.isArray(this.$events[a])?this.$events[a].push(f):this.$events[a]=[this.$events[a],f]:this.$events[a]=f;return this};e.prototype.addListener=e.prototype.on;e.prototype.once=function(a,f){function c(){b.removeListener(a,c);f.apply(this,arguments)}var b=this;c.listener=f;this.on(a,c);return this};e.prototype.removeListener=function(a,f){if(this.$events&&this.$events[a]){var c=
this.$events[a];if(d.util.isArray(c)){for(var b=-1,h=0,e=c.length;h<e;h++)if(c[h]===f||c[h].listener&&c[h].listener===f){b=h;break}if(0>b)return this;c.splice(b,1);c.length||delete this.$events[a]}else(c===f||c.listener&&c.listener===f)&&delete this.$events[a]}return this};e.prototype.removeAllListeners=function(a){this.$events&&this.$events[a]&&(this.$events[a]=null);return this};e.prototype.listeners=function(a){this.$events||(this.$events={});this.$events[a]||(this.$events[a]=[]);d.util.isArray(this.$events[a])||
(this.$events[a]=[this.$events[a]]);return this.$events[a]};e.prototype.emit=function(a){if(!this.$events)return!1;var f=this.$events[a];if(!f)return!1;var c=Array.prototype.slice.call(arguments,1);if("function"==typeof f)f.apply(this,c);else if(d.util.isArray(f))for(var f=f.slice(),b=0,h=f.length;b<h;b++)f[b].apply(this,c);else return!1;return!0}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(g,d){function e(b){return 10>b?"0"+b:b}function a(b){h.lastIndex=0;return h.test(b)?'"'+b.replace(h,function(b){var c=j[b];return"string"===typeof c?c:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function f(b,c){var h,d,j,g,q=k,o,l=c[b];l instanceof Date&&(l=isFinite(b.valueOf())?b.getUTCFullYear()+"-"+e(b.getUTCMonth()+1)+"-"+e(b.getUTCDate())+"T"+e(b.getUTCHours())+":"+e(b.getUTCMinutes())+":"+e(b.getUTCSeconds())+"Z":null);"function"===typeof i&&(l=i.call(c,b,
l));switch(typeof l){case "string":return a(l);case "number":return isFinite(l)?""+l:"null";case "boolean":case "null":return""+l;case "object":if(!l)return"null";k+=p;o=[];if("[object Array]"===Object.prototype.toString.apply(l)){g=l.length;for(h=0;h<g;h+=1)o[h]=f(h,l)||"null";j=0===o.length?"[]":k?"[\n"+k+o.join(",\n"+k)+"\n"+q+"]":"["+o.join(",")+"]";k=q;return j}if(i&&"object"===typeof i){g=i.length;for(h=0;h<g;h+=1)"string"===typeof i[h]&&(d=i[h],(j=f(d,l))&&o.push(a(d)+(k?": ":":")+j))}else for(d in l)Object.prototype.hasOwnProperty.call(l,
d)&&(j=f(d,l))&&o.push(a(d)+(k?": ":":")+j);j=0===o.length?"{}":k?"{\n"+k+o.join(",\n"+k)+"\n"+q+"}":"{"+o.join(",")+"}";k=q;return j}}if(d&&d.parse)return g.JSON={parse:d.parse,stringify:d.stringify};var c=g.JSON={},b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,k,p,j={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f",
"\r":"\\r",'"':'\\"',"\\":"\\\\"},i;c.stringify=function(b,c,a){var h;p=k="";if("number"===typeof a)for(h=0;h<a;h+=1)p+=" ";else"string"===typeof a&&(p=a);if((i=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return f("",{"":b})};c.parse=function(c,a){function h(b,c){var f,d,e=b[c];if(e&&"object"===typeof e)for(f in e)Object.prototype.hasOwnProperty.call(e,f)&&(d=h(e,f),void 0!==d?e[f]=d:delete e[f]);return a.call(b,c,e)}var f,c=""+c;b.lastIndex=
0;b.test(c)&&(c=c.replace(b,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(c.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=eval("("+c+")"),"function"===typeof a?h({"":f},""):f;throw new SyntaxError("JSON.parse");}})("undefined"!=typeof io?io:module.exports,"undefined"!==typeof JSON?JSON:void 0);
(function(g,d){var e=g.parser={},a=e.packets="disconnect,connect,heartbeat,message,json,event,ack,error,noop".split(","),f=e.reasons=["transport not supported","client not handshaken","unauthorized"],c=e.advice=["reconnect"],b=d.JSON,h=d.util.indexOf;e.encodePacket=function(d){var e=h(a,d.type),i=d.id||"",k=d.endpoint||"",g=d.ack,m=null;switch(d.type){case "error":var s=d.reason?h(f,d.reason):"",d=d.advice?h(c,d.advice):"";if(""!==s||""!==d)m=s+(""!==d?"+"+d:"");break;case "message":""!==d.data&&
(m=d.data);break;case "event":m={name:d.name};d.args&&d.args.length&&(m.args=d.args);m=b.stringify(m);break;case "json":m=b.stringify(d.data);break;case "connect":d.qs&&(m=d.qs);break;case "ack":m=d.ackId+(d.args&&d.args.length?"+"+b.stringify(d.args):"")}e=[e,i+("data"==g?"+":""),k];null!==m&&void 0!==m&&e.push(m);return e.join(":")};e.encodePayload=function(b){var c="";if(1==b.length)return b[0];for(var a=0,d=b.length;a<d;a++)c+="\ufffd"+b[a].length+"\ufffd"+b[a];return c};var k=/([^:]+):([0-9]+)?(\+)?:([^:]+)?:?([\s\S]*)?/;
e.decodePacket=function(d){var h=d.match(k);if(!h)return{};var e=h[2]||"",d=h[5]||"",g={type:a[h[1]],endpoint:h[4]||""};e&&(g.id=e,g.ack=h[3]?"data":!0);switch(g.type){case "error":h=d.split("+");g.reason=f[h[0]]||"";g.advice=c[h[1]]||"";break;case "message":g.data=d||"";break;case "event":try{var n=b.parse(d);g.name=n.name;g.args=n.args}catch(m){}g.args=g.args||[];break;case "json":try{g.data=b.parse(d)}catch(s){}break;case "connect":g.qs=d||"";break;case "ack":if(h=d.match(/^([0-9]+)(\+)?(.*)/))if(g.ackId=
h[1],g.args=[],h[3])try{g.args=h[3]?b.parse(h[3]):[]}catch(t){}}return g};e.decodePayload=function(b){if("\ufffd"==b.charAt(0)){for(var c=[],a=1,d="";a<b.length;a++)"\ufffd"==b.charAt(a)?(c.push(e.decodePacket(b.substr(a+1).substr(0,d))),a+=Number(d)+1,d=""):d+=b.charAt(a);return c}return[e.decodePacket(b)]}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(g,d){function e(a,d){this.socket=a;this.sessid=d}g.Transport=e;d.util.mixin(e,d.EventEmitter);e.prototype.onData=function(a){this.clearCloseTimeout();(this.connected||this.connecting||this.reconnecting)&&this.setCloseTimeout();if(""!==a&&(a=d.parser.decodePayload(a))&&a.length)for(var f=0,c=a.length;f<c;f++)this.onPacket(a[f]);return this};e.prototype.onPacket=function(a){if("heartbeat"==a.type)return this.onHeartbeat();if("connect"==a.type&&""==a.endpoint)this.onConnect();this.socket.onPacket(a);
return this};e.prototype.setCloseTimeout=function(){if(!this.closeTimeout){var a=this;this.closeTimeout=setTimeout(function(){a.onDisconnect()},this.socket.closeTimeout)}};e.prototype.onDisconnect=function(){this.close&&this.open&&this.close();this.clearTimeouts();this.socket.onDisconnect();return this};e.prototype.onConnect=function(){this.socket.onConnect();return this};e.prototype.clearCloseTimeout=function(){this.closeTimeout&&(clearTimeout(this.closeTimeout),this.closeTimeout=null)};e.prototype.clearTimeouts=
function(){this.clearCloseTimeout();this.reopenTimeout&&clearTimeout(this.reopenTimeout)};e.prototype.packet=function(a){this.send(d.parser.encodePacket(a))};e.prototype.onHeartbeat=function(){this.packet({type:"heartbeat"})};e.prototype.onOpen=function(){this.open=!0;this.clearCloseTimeout();this.socket.onOpen()};e.prototype.onClose=function(){this.open=!1;this.socket.onClose();this.onDisconnect()};e.prototype.prepareUrl=function(){var a=this.socket.options;return this.scheme()+"://"+a.host+":"+
a.port+"/"+a.resource+"/"+d.protocol+"/"+this.name+"/"+this.sessid};e.prototype.ready=function(a,d){d.call(this)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(g,d,e){function a(c){this.options={port:80,secure:!1,document:"document"in e?document:!1,resource:"socket.io",transports:d.transports,"connect timeout":1E4,"try multiple transports":!0,reconnect:!0,"reconnection delay":500,"reconnection limit":Infinity,"reopen delay":3E3,"max reconnection attempts":10,"sync disconnect on unload":!0,"auto connect":!0,"flash policy port":10843};d.util.merge(this.options,c);this.reconnecting=this.connecting=this.open=this.connected=!1;this.namespaces={};this.buffer=
[];this.doBuffer=!1;if(this.options["sync disconnect on unload"]&&(!this.isXDomain()||d.util.ua.hasCORS)){var b=this;d.util.on(e,"beforeunload",function(){b.disconnectSync()},!1)}this.options["auto connect"]&&this.connect()}function f(){}g.Socket=a;d.util.mixin(a,d.EventEmitter);a.prototype.of=function(c){this.namespaces[c]||(this.namespaces[c]=new d.SocketNamespace(this,c),""!==c&&this.namespaces[c].packet({type:"connect"}));return this.namespaces[c]};a.prototype.publish=function(){this.emit.apply(this,
arguments);var c,b;for(b in this.namespaces)this.namespaces.hasOwnProperty(b)&&(c=this.of(b),c.$emit.apply(c,arguments))};a.prototype.handshake=function(c){function b(b){if(b instanceof Error)a.onError(b.message);else c.apply(null,b.split(":"))}var a=this,e=this.options,e=["http"+(e.secure?"s":"")+":/",e.host+":"+e.port,e.resource,d.protocol,d.util.query(this.options.query,"t="+ +new Date)].join("/");if(this.isXDomain()&&!d.util.ua.hasCORS){var g=document.getElementsByTagName("script")[0],j=document.createElement("script");
j.src=e+"&jsonp="+d.j.length;g.parentNode.insertBefore(j,g);d.j.push(function(c){b(c);j.parentNode.removeChild(j)})}else{var i=d.util.request();i.open("GET",e,!0);i.onreadystatechange=function(){4==i.readyState&&(i.onreadystatechange=f,200==i.status?b(i.responseText):!a.reconnecting&&a.onError(i.responseText))};i.send(null)}};a.prototype.getTransport=function(c){for(var c=c||this.transports,b=0,a;a=c[b];b++)if(d.Transport[a]&&d.Transport[a].check(this)&&(!this.isXDomain()||d.Transport[a].xdomainCheck()))return new d.Transport[a](this,
this.sessionid);return null};a.prototype.connect=function(c){if(this.connecting)return this;var b=this;this.handshake(function(a,f,e,g){function i(c){b.transport&&b.transport.clearTimeouts();b.transport=b.getTransport(c);if(!b.transport)return b.publish("connect_failed");b.transport.ready(b,function(){b.connecting=!0;b.publish("connecting",b.transport.name);b.transport.open();b.options["connect timeout"]&&(b.connectTimeoutTimer=setTimeout(function(){if(!b.connected&&(b.connecting=!1,b.options["try multiple transports"])){b.remainingTransports||
(b.remainingTransports=b.transports.slice(0));for(var c=b.remainingTransports;0<c.length&&c.splice(0,1)[0]!=b.transport.name;);c.length?i(c):b.publish("connect_failed")}},b.options["connect timeout"]))})}b.sessionid=a;b.closeTimeout=1E3*e;b.heartbeatTimeout=1E3*f;b.transports=d.util.intersect(g.split(","),b.options.transports);i();b.once("connect",function(){clearTimeout(b.connectTimeoutTimer);c&&"function"==typeof c&&c()})});return this};a.prototype.packet=function(c){this.connected&&!this.doBuffer?
this.transport.packet(c):this.buffer.push(c);return this};a.prototype.setBuffer=function(c){this.doBuffer=c;!c&&this.connected&&this.buffer.length&&(this.transport.payload(this.buffer),this.buffer=[])};a.prototype.disconnect=function(){this.connected&&(this.open&&this.of("").packet({type:"disconnect"}),this.onDisconnect("booted"));return this};a.prototype.disconnectSync=function(){d.util.request().open("GET",this.resource+"/"+d.protocol+"/"+this.sessionid,!0);this.onDisconnect("booted")};a.prototype.isXDomain=
function(){var c=e.location.port||("https:"==e.location.protocol?443:80);return this.options.host!==e.location.hostname||this.options.port!=c};a.prototype.onConnect=function(){this.connected||(this.connected=!0,this.connecting=!1,this.doBuffer||this.setBuffer(!1),this.emit("connect"))};a.prototype.onOpen=function(){this.open=!0};a.prototype.onClose=function(){this.open=!1};a.prototype.onPacket=function(c){this.of(c.endpoint).onPacket(c)};a.prototype.onError=function(c){c&&c.advice&&"reconnect"===
c.advice&&this.connected&&(this.disconnect(),this.reconnect());this.publish("error",c&&c.reason?c.reason:c)};a.prototype.onDisconnect=function(c){var b=this.connected;this.open=this.connecting=this.connected=!1;b&&(this.transport.close(),this.transport.clearTimeouts(),this.publish("disconnect",c),"booted"!=c&&this.options.reconnect&&!this.reconnecting&&this.reconnect())};a.prototype.reconnect=function(){function c(){if(a.connected){for(var c in a.namespaces)a.namespaces.hasOwnProperty(c)&&""!==c&&
a.namespaces[c].packet({type:"connect"});a.publish("reconnect",a.transport.name,a.reconnectionAttempts)}a.removeListener("connect_failed",b);a.removeListener("connect",b);a.reconnecting=!1;delete a.reconnectionAttempts;delete a.reconnectionDelay;delete a.reconnectionTimer;delete a.redoTransports;a.options["try multiple transports"]=f}function b(){if(a.reconnecting){if(a.connected)return c();if(a.connecting&&a.reconnecting)return a.reconnectionTimer=setTimeout(b,1E3);a.reconnectionAttempts++>=d?a.redoTransports?
(a.publish("reconnect_failed"),c()):(a.on("connect_failed",b),a.options["try multiple transports"]=!0,a.transport=a.getTransport(),a.redoTransports=!0,a.connect()):(a.reconnectionDelay<e&&(a.reconnectionDelay*=2),a.connect(),a.publish("reconnecting",a.reconnectionDelay,a.reconnectionAttempts),a.reconnectionTimer=setTimeout(b,a.reconnectionDelay))}}this.reconnecting=!0;this.reconnectionAttempts=0;this.reconnectionDelay=this.options["reconnection delay"];var a=this,d=this.options["max reconnection attempts"],
f=this.options["try multiple transports"],e=this.options["reconnection limit"];this.options["try multiple transports"]=!1;this.reconnectionTimer=setTimeout(b,this.reconnectionDelay);this.on("connect",b)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(g,d){function e(d,c){this.socket=d;this.name=c||"";this.flags={};this.json=new a(this,"json");this.ackPackets=0;this.acks={}}function a(a,c){this.namespace=a;this.name=c}g.SocketNamespace=e;d.util.mixin(e,d.EventEmitter);e.prototype.$emit=d.EventEmitter.prototype.emit;e.prototype.of=function(){return this.socket.of.apply(this.socket,arguments)};e.prototype.packet=function(a){a.endpoint=this.name;this.socket.packet(a);this.flags={};return this};e.prototype.send=function(a,c){var b={type:this.flags.json?
"json":"message",data:a};"function"==typeof c&&(b.id=++this.ackPackets,b.ack=!0,this.acks[b.id]=c);return this.packet(b)};e.prototype.emit=function(a){var c=Array.prototype.slice.call(arguments,1),b=c[c.length-1],d={type:"event",name:a};"function"==typeof b&&(d.id=++this.ackPackets,d.ack="data",this.acks[d.id]=b,c=c.slice(0,c.length-1));d.args=c;return this.packet(d)};e.prototype.disconnect=function(){""===this.name?this.socket.disconnect():(this.packet({type:"disconnect"}),this.$emit("disconnect"));
return this};e.prototype.onPacket=function(a){function c(){b.packet({type:"ack",args:d.util.toArray(arguments),ackId:a.id})}var b=this;switch(a.type){case "connect":this.$emit("connect");break;case "disconnect":if(""===this.name)this.socket.onDisconnect(a.reason||"booted");else this.$emit("disconnect",a.reason);break;case "message":case "json":var e=["message",a.data];"data"==a.ack?e.push(c):a.ack&&this.packet({type:"ack",ackId:a.id});this.$emit.apply(this,e);break;case "event":e=[a.name].concat(a.args);
"data"==a.ack&&e.push(c);this.$emit.apply(this,e);break;case "ack":this.acks[a.ackId]&&(this.acks[a.ackId].apply(this,a.args),delete this.acks[a.ackId]);break;case "error":if(a.advice)this.socket.onError(a);else"unauthorized"==a.reason?this.$emit("connect_failed",a.reason):this.$emit("error",a.reason)}};a.prototype.send=function(){this.namespace.flags[this.name]=!0;this.namespace.send.apply(this.namespace,arguments)};a.prototype.emit=function(){this.namespace.flags[this.name]=!0;this.namespace.emit.apply(this.namespace,
arguments)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(g,d,e){function a(a){d.Transport.apply(this,arguments)}g.websocket=a;d.util.inherit(a,d.Transport);a.prototype.name="websocket";a.prototype.open=function(){var a=d.util.query(this.socket.options.query),c=this,b;b||(b=e.MozWebSocket||e.WebSocket);this.websocket=new b(this.prepareUrl()+a);this.websocket.onopen=function(){c.onOpen();c.socket.setBuffer(!1)};this.websocket.onmessage=function(a){c.onData(a.data)};this.websocket.onclose=function(){c.onClose();c.socket.setBuffer(!0)};this.websocket.onerror=
function(a){c.onError(a)};return this};a.prototype.send=function(a){this.websocket.send(a);return this};a.prototype.payload=function(a){for(var c=0,b=a.length;c<b;c++)this.packet(a[c]);return this};a.prototype.close=function(){this.websocket.close();return this};a.prototype.onError=function(a){this.socket.onError(a)};a.prototype.scheme=function(){return this.socket.options.secure?"wss":"ws"};a.check=function(){return"WebSocket"in e&&!("__addTask"in WebSocket)||"MozWebSocket"in e};a.xdomainCheck=function(){return!0};
d.transports.push("websocket")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(g,d,e){function a(a){a&&(d.Transport.apply(this,arguments),this.sendBuffer=[])}function f(){}g.XHR=a;d.util.inherit(a,d.Transport);a.prototype.open=function(){this.socket.setBuffer(!1);this.onOpen();this.get();this.setCloseTimeout();return this};a.prototype.payload=function(a){for(var b=[],e=0,f=a.length;e<f;e++)b.push(d.parser.encodePacket(a[e]));this.send(d.parser.encodePayload(b))};a.prototype.send=function(a){this.post(a);return this};a.prototype.post=function(a){function b(){if(4==
this.readyState)if(this.onreadystatechange=f,g.posting=!1,200==this.status)g.socket.setBuffer(!1);else g.onClose()}function d(){this.onload=f;g.socket.setBuffer(!1)}var g=this;this.socket.setBuffer(!0);this.sendXHR=this.request("POST");e.XDomainRequest&&this.sendXHR instanceof XDomainRequest?this.sendXHR.onload=this.sendXHR.onerror=d:this.sendXHR.onreadystatechange=b;this.sendXHR.send(a)};a.prototype.close=function(){this.onClose();return this};a.prototype.request=function(a){var b=d.util.request(this.socket.isXDomain()),
e=d.util.query(this.socket.options.query,"t="+ +new Date);b.open(a||"GET",this.prepareUrl()+e,!0);if("POST"==a)try{b.setRequestHeader?b.setRequestHeader("Content-type","text/plain;charset=UTF-8"):b.contentType="text/plain"}catch(f){}return b};a.prototype.scheme=function(){return this.socket.options.secure?"https":"http"};a.check=function(a,b){try{if(d.util.request(b))return!0}catch(e){}return!1};a.xdomainCheck=function(){return a.check(null,!0)}})("undefined"!=typeof io?io.Transport:module.exports,
"undefined"!=typeof io?io:module.parent.exports,this);
(function(g,d){function e(a){d.Transport.XHR.apply(this,arguments)}g.htmlfile=e;d.util.inherit(e,d.Transport.XHR);e.prototype.name="htmlfile";e.prototype.get=function(){this.doc=new ActiveXObject("htmlfile");this.doc.open();this.doc.write("<html></html>");this.doc.close();this.doc.parentWindow.s=this;var a=this.doc.createElement("div");a.className="socketio";this.doc.body.appendChild(a);this.iframe=this.doc.createElement("iframe");a.appendChild(this.iframe);var e=this,a=d.util.query(this.socket.options.query,
"t="+ +new Date);this.iframe.src=this.prepareUrl()+a;d.util.on(window,"unload",function(){e.destroy()})};e.prototype._=function(a,d){this.onData(a);try{var c=d.getElementsByTagName("script")[0];c.parentNode.removeChild(c)}catch(b){}};e.prototype.destroy=function(){if(this.iframe){try{this.iframe.src="about:blank"}catch(a){}this.doc=null;this.iframe.parentNode.removeChild(this.iframe);this.iframe=null;CollectGarbage()}};e.prototype.close=function(){this.destroy();return d.Transport.XHR.prototype.close.call(this)};
e.check=function(){if("ActiveXObject"in window)try{return new ActiveXObject("htmlfile")&&d.Transport.XHR.check()}catch(a){}return!1};e.xdomainCheck=function(){return!1};d.transports.push("htmlfile")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(g,d,e){function a(){d.Transport.XHR.apply(this,arguments)}function f(){}g["xhr-polling"]=a;d.util.inherit(a,d.Transport.XHR);d.util.merge(a,d.Transport.XHR);a.prototype.name="xhr-polling";a.prototype.open=function(){d.Transport.XHR.prototype.open.call(this);return!1};a.prototype.get=function(){function a(){if(4==this.readyState)if(this.onreadystatechange=f,200==this.status)d.onData(this.responseText),d.get();else d.onClose()}function b(){this.onload=f;d.onData(this.responseText);d.get()}
if(this.open){var d=this;this.xhr=this.request();e.XDomainRequest&&this.xhr instanceof XDomainRequest?this.xhr.onload=this.xhr.onerror=b:this.xhr.onreadystatechange=a;this.xhr.send(null)}};a.prototype.onClose=function(){d.Transport.XHR.prototype.onClose.call(this);if(this.xhr){this.xhr.onreadystatechange=this.xhr.onload=f;try{this.xhr.abort()}catch(a){}this.xhr=null}};a.prototype.ready=function(a,b){var e=this;d.util.defer(function(){b.call(e)})};d.transports.push("xhr-polling")})("undefined"!=typeof io?
io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(g,d,e){function a(a){d.Transport["xhr-polling"].apply(this,arguments);this.index=d.j.length;var b=this;d.j.push(function(a){b._(a)})}var f=e.document&&"MozAppearance"in e.document.documentElement.style;g["jsonp-polling"]=a;d.util.inherit(a,d.Transport["xhr-polling"]);a.prototype.name="jsonp-polling";a.prototype.post=function(a){function b(){e();f.socket.setBuffer(!1)}function e(){f.iframe&&f.form.removeChild(f.iframe);try{n=document.createElement('<iframe name="'+f.iframeId+'">')}catch(a){n=
document.createElement("iframe"),n.name=f.iframeId}n.id=f.iframeId;f.form.appendChild(n);f.iframe=n}var f=this,g=d.util.query(this.socket.options.query,"t="+ +new Date+"&i="+this.index);if(!this.form){var j=document.createElement("form"),i=document.createElement("textarea"),r=this.iframeId="socketio_iframe_"+this.index,n;j.className="socketio";j.style.position="absolute";j.style.top="-1000px";j.style.left="-1000px";j.target=r;j.method="POST";j.setAttribute("accept-charset","utf-8");i.name="d";j.appendChild(i);
document.body.appendChild(j);this.form=j;this.area=i}this.form.action=this.prepareUrl()+g;e();this.area.value=d.JSON.stringify(a);try{this.form.submit()}catch(m){}this.iframe.attachEvent?n.onreadystatechange=function(){"complete"==f.iframe.readyState&&b()}:this.iframe.onload=b;this.socket.setBuffer(!0)};a.prototype.get=function(){var a=this,b=document.createElement("script"),e=d.util.query(this.socket.options.query,"t="+ +new Date+"&i="+this.index);this.script&&(this.script.parentNode.removeChild(this.script),
this.script=null);b.async=!0;b.src=this.prepareUrl()+e;b.onerror=function(){a.onClose()};e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(b,e);this.script=b;f&&setTimeout(function(){var a=document.createElement("iframe");document.body.appendChild(a);document.body.removeChild(a)},100)};a.prototype._=function(a){this.onData(a);this.open&&this.get();return this};a.prototype.ready=function(a,b){var e=this;if(!f)return b.call(this);d.util.load(function(){b.call(e)})};a.check=function(){return"document"in
e};a.xdomainCheck=function(){return!0};d.transports.push("jsonp-polling")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
